### ISSUE TITLE
Forwarding service from Linkwatch Cloud to CAMI Cloud

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#223]
## Why
Following the analysis in #216, the fastest way to achieve an integration of measurements from the iOS Linkwatch Data Collector into CAMI is to set up a forwarding service in the Linkwatch Cloud that makes API calls to the CAMI cloud (see [documentation here](https://github.com/cami-project/cami-project/blob/master/store/README.md)).

## What
  - [ ] an export service is created within the Linkwatch Cloud that translates the from the openMHealth schema to the current CAMI measurement schema
  - [ ] device entries for the UA-651 BLE blood pressure monitor and Fitbit are created through the [Django admin interface on the dev machine](http://141.85.241.224:8008/admin/).
  - [ ] test measurement forwarding end report errors

## Notes
After successful integration and testing it remains an open issue to create openMHealth compatible endpoints directly into CAMI.
This task will be tackled after obtaining the first CAMI MVP to be used within early field trials.

**Comment by tobiasbrodencnet** [comment]
During the past week data are now forwad from our CNetDemo account into CAMI store, to make sure that it's working correctly. The user used is the CAMI demo with userUrl: /api/v1/user/2/. Data are forward for weight on deviceUrl: /api/v1/device/3/ and blood pressure on deviceUrl: /api/v1/device/4/. 

To forward data from FitBit was a bit more complicated than expected. In LinkWatch we populate the FitBit data every hour for that day. Steps are for instance set to 0 default in the FitBit API. Which means that we may need to update old populated measurements. Not sure how to forward this. Think it would be best to create a seperate task for this. 

Furthermore in order to activate the forwarding on an account in LinkWatch.
- Have an account
- Manual add which measurement types to forward. Done on device level (e.g. all measurement from blood pressure device for a user). 
- Manual add userUrl and deviceUrl to indentify the user that the data belongs to in CAMI store.

And in CAMI store.
- Create the device and fetch the deviceUrl.
