### ISSUE TITLE
Investigate creating separate container for Google Fit integration

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#246]
## Why
Following our talks and planning in #221, we have decided to separate the 3rd party services currently residing in the `medical_compliance` container into more targeted, individual containers.

The Google Fit service is used as a middleware for information on number of steps and heart rate gathered from the LG smartwatch.

## What
* [x] splitting the `google_fit` service container is investigated and the plan is posted on this issue as a comment
* [ ] follow-up issues are created to implement it

## Notes
The Google Fit service will not be handling processing and analysis of the health data, but rather only deal w/ fetching the information from the API and forwarding it to the containers that require it. 

The analysis (ex: deciding if a measurement is in normal params or if it should trigger a client notification) will be handled by a separate container.

**Comment by cretualexandru** [comment]
Finished the investigation on this. This is the plan:

1. Create the `contractor` container, which will handle the measurements analysis and storing
2. Split the Google Fit related code into a new container
3. Modify iOS application to fetch `heartrate` and `steps` measurements through the`store` API
4. Split the Withings related code into a new container
5. Modify iOS application to fetch `weight` measurements through the`store` API 
6. Remove the old `medical_compliance` container

The `google_fit` and `withings` containers will fetch the measurements from their services and will broadcast them on a measurements queue. `contractor`, `linkwatch` and `opentele` will listen to that queue, receiving the measurements and processing them.

`contractor` will analyze the received values and will save them in the `store`(using the API) alongside an `ok` value: `True` if the measurement value reflects a healthy state, `False` otherwise. If the value is not ok, a notification will also be triggered and a **journal entry** will be created by the `contractor` and saved in the `store`.

`linkwatch` and `opentele` will continue to work as they do now, but will probably need some minor modifications.

We'll execute the plan following the exact order of the steps listed above in order not to "break the build" and keep the project working properly all along the clean-up process.

**Comment by cretualexandru** [comment]
This is no longer usable, we will create a fresh `medical_compliance` refactoring plan after we finish the reminders implementation.
