### ISSUE TITLE
Improvement requests in CAMI iOS app

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#424]
## Why
The iOS application was built to validate many design and functionality decisions in CAMI.
Currently, it contains many defaults in terms of its UI.
However, for the upcoming first stage field trials, we need to present a neutral interface, such that it may be tested by the end users.

The following are suggested as improvements by the end-user partners:

## What
  - [x] Change the phrasing of "Your loved one is doing fine" from the Home screen to "All is fine"
  - [x] remove the picture of "Jim" and replace it with an icon if 
  - [x] the latest journal entries on the home screen should have a _date_ attached to them. Just the hour may be confusing since it may refer to the previous day, or even longer ago, if the user has had no worrisome activity

  - [x] the reminders / notifications in the end-user application should also show the `description` part of the journal entry (currently they display only the `message` part)

**Comment by rtud** [comment]
@asorici: regarding the 3rd checkbox _"the latest journal entries on the home screen should have a date attached to them."_ -- we're already displaying day separators inside the application:

![date separators in the Caregiver's Journal view](http://mq.d.pr/QMyYLD.jpg)

This design decision was made in order to declutter the Journal view of bulky, recurring elements.

Thank you!

**Comment by rtud** [comment]
This issue has been handled in #369, closing, thank you!
